import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { headers } from 'next/headers';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const token = headersList.get('x-whop-user-token');

  // Always render script tag with empty string if no token to avoid hydration mismatch
  const tokenValue = token || '';

  return (
    <html lang="en">
      <head>
        {/* Move script to head and always render for consistent SSR/hydration */}
        <script
          dangerouslySetInnerHTML={{
            __html: `window.WHOP_TOKEN = ${JSON.stringify(tokenValue)};`,
          }}
        />
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
