import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { headers } from 'next/headers';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const token = headersList.get('x-whop-user-token');
  return (
    <html lang="en">
      <body className={inter.className}>
        {token && (
          <script
            dangerouslySetInnerHTML={{
              __html: `window.WHOP_TOKEN = "${token}";`,
            }}
          />
        )}
        {children}
      </body>
    </html>
  );
}
